
INSERT INTO T_ADMIN_ROLE (F_ADMIN_ROLE_ID, F_ADMIN_ROLE_NAME, F_ADMIN_ROLE_DESC) VALUES (1, '超级管理员', '超级管理员');

INSERT INTO T_ADMIN_RIGHT (F_ADMIN_RIGHT_ID, F_ADMIN_RIGHT_PARENT_ID, F_ADMIN_RIGHT_NAME, F_ADMIN_RIGHT_DESC, F_ADMIN_RIGHT_ICON, F_ADMIN_RIGHT_MODEL, F_ADMIN_RIGHT_ACTION, F_ADMIN_RIGHT_IS_MENU) VALUES (1, 0, '管理员权限', '管理员权限', '&#xe6b8;', '', '', 1);
INSERT INTO T_ADMIN_RIGHT (F_ADMIN_RIGHT_ID, F_ADMIN_RIGHT_PARENT_ID, F_ADMIN_RIGHT_NAME, F_ADMIN_RIGHT_DESC, F_ADMIN_RIGHT_ICON, F_ADMIN_RIGHT_MODEL, F_ADMIN_RIGHT_ACTION, F_ADMIN_RIGHT_IS_MENU) VALUES (2, 1, '管理员管理', '管理员管理', '', '/admin/adminer/', 'index', 1);
INSERT INTO T_ADMIN_RIGHT (F_ADMIN_RIGHT_ID, F_ADMIN_RIGHT_PARENT_ID, F_ADMIN_RIGHT_NAME, F_ADMIN_RIGHT_DESC, F_ADMIN_RIGHT_ICON, F_ADMIN_RIGHT_MODEL, F_ADMIN_RIGHT_ACTION, F_ADMIN_RIGHT_IS_MENU) VALUES (3, 1, '角色管理', '角色管理', '', '/admin/role/', 'index', 1);

INSERT INTO T_ADMIN_ROLE_RIGHT_RL (T_ADMIN_RIGHT_id, F_ADMIN_ROLE_ID) VALUES (1, 1);
INSERT INTO T_ADMIN_ROLE_RIGHT_RL (T_ADMIN_RIGHT_id, F_ADMIN_ROLE_ID) VALUES (2, 1);
INSERT INTO T_ADMIN_ROLE_RIGHT_RL (T_ADMIN_RIGHT_id, F_ADMIN_ROLE_ID) VALUES (3, 1);
