
INSERT INTO T_ADMIN_ROLE (F_ADMIN_ROLE_ID, F_ADMIN_ROLE_NAME, F_ADMIN_ROLE_DESC) VALUES (1, '超级管理员', '超级管理员');

INSERT INTO T_ADMIN_MENU (F_ADMIN_MENU_ID, F_ADMIN_MENU_PARENT_ID, F_ADMIN_MENU_NAME, F_ADMIN_MENU_DESC, F_ADMIN_MENU_ICON, F_ADMIN_MENU_MODEL, F_ADMIN_MENU_ACTION) VALUES (1, 0, '管理员权限', '管理员权限', '&#xe6b8;', '', '');
INSERT INTO T_ADMIN_MENU (F_ADMIN_MENU_ID, F_ADMIN_MENU_PARENT_ID, F_ADMIN_MENU_NAME, F_ADMIN_MENU_DESC, F_ADMIN_MENU_ICON, F_ADMIN_MENU_MODEL, F_ADMIN_MENU_ACTION) VALUES (2, 1, '管理员管理', '管理员管理', '', '/admin/adminer/', 'index');
INSERT INTO T_ADMIN_MENU (F_ADMIN_MENU_ID, F_ADMIN_MENU_PARENT_ID, F_ADMIN_MENU_NAME, F_ADMIN_MENU_DESC, F_ADMIN_MENU_ICON, F_ADMIN_MENU_MODEL, F_ADMIN_MENU_ACTION) VALUES (3, 1, '角色管理', '角色管理', '', '/admin/role/', 'index');

INSERT INTO T_ADMIN_ROLE_MENU_RL (T_ADMIN_MENU_id, F_ADMIN_ROLE_ID) VALUES (1, 1);
INSERT INTO T_ADMIN_ROLE_MENU_RL (T_ADMIN_MENU_id, F_ADMIN_ROLE_ID) VALUES (2, 1);
INSERT INTO T_ADMIN_ROLE_MENU_RL (T_ADMIN_MENU_id, F_ADMIN_ROLE_ID) VALUES (3, 1);
